### ISSUE TITLE
Seems like i386 wireguard-tools package is broken

### ISSUE THREAD

**Issue by cryptofuture** [EggieCode/wireguard-ppa#13]
From maillist:
> Hello,
> 
> I've been trying to setup wireguard to experiment with it a bit and I've 
> run into a problem.  The i386 wireguard-tools package on the PPA for 
> Ubuntu Xenial doesn't actually contain any of the binaries, just 
> documentation.  You see this by checking the file listing at the end of 
> the build log here

> arm and ppc64 packages are also missing
> binaries.

Looking into it now. But from what moment we have ppc64 and arm builds activated for ppa?  
Pretty sure this is not default.

**Comment by cryptofuture** [comment]
Thats fun, since I can reproduce issue only on launchpad. i386 package is correct in build env.

**Comment by EggieCode** [comment]
You have update the PPA already? Was just going to test it om my Pi.
(Mail server was down for the night, needed some catching up)

**Comment by EggieCode** [comment]
Old item in the wg mailinglist: https://lists.zx2c4.com/pipermail/wireguard/2017-February/001050.html

**Comment by cryptofuture** [comment]
Nope, I tested launchpad in own dump ppa.  
I didn't ever tested arm or ppc64, and was even didn't aware someone enabled it for ppa.

**Comment by EggieCode** [comment]
I dit I think. Got arm enabled on your repo? Can test it on my PI.
And going to test for 17.04

**Comment by cryptofuture** [comment]
Nope, I can check only package context on arm or ppc64, I didn't have anything real on arm or ppc.  
Try referenced pull request, works for i386 for me.

**Comment by EggieCode** [comment]
Cool. Can you enable it for me? So I can test it om my Pi?

**Comment by cryptofuture** [comment]
I reuploaded and enabled the same architectures, we have currently enabled in official ppa in dump ppa  
Check it [here](https://launchpad.net/~hda-me/+archive/ubuntu/wireguard), when it'll be published.
