### ISSUE TITLE
Bump to 0.0.20170517

### ISSUE THREAD

**Issue by zx2c4** [EggieCode/wireguard-ppa#18]
https://lists.zx2c4.com/pipermail/wireguard/2017-May/001334.html

This is a rather important release, so let's get this bumped soon.

**Comment by EggieCode** [comment]
Well be updated in 15min. Need to test first.

**Comment by EggieCode** [comment]
Push to git: be4bedb6c06d77bbe2526460afd0188da54bc3ae
Launchpad is build the packages, will take a minute or 2.

**Comment by zx2c4** [comment]
Great!
