### ISSUE TITLE
Can build 0.0.20170629 for trusty i386 only with hack

### ISSUE THREAD

**Issue by cryptofuture** [EggieCode/wireguard-ppa#22]
Trusty i386 package build fails under every env with our current rules file (pbuilder, launchpad, real i386 trusty in kvm).
I can build it only with such hack, and surely i don't like it.

```bash
#!/usr/bin/make -f

include /usr/share/dpkg/default.mk

export DEB_BUILD_MAINT_OPTIONS = hardening=+all

%:
	dh $@ --with dkms

override_dh_auto_install-indep:
	mkdir -p $(CURDIR)/debian/wireguard-dkms/usr/src
	cp -a $(CURDIR)/wireguard-src/src $(CURDIR)/debian/wireguard-dkms/usr/src/wireguard-$(DEB_VERSION_UPSTREAM)/
	$(MAKE) -C wireguard-src/src DESTDIR=$(CURDIR)/debian/wireguard-dkms DKMSDIR=/usr/src/wireguard-$(DEB_VERSION_UPSTREAM)/ dkms-install

override_dh_auto_install-arch:
	$(MAKE) -C wireguard-src/src/tools DESTDIR=$(CURDIR)/debian/wireguard-tools WITH_SYSTEMDUNITS=yes WITH_WGQUICK=yes WITH_BASHCOMPLETION=yes install

override_dh_auto_build-arch:
	$(MAKE) -C wireguard-src/src/tools WITH_SYSTEMDUNITS=yes WITH_WGQUICK=yes WITH_BASHCOMPLETION=yes

override_dh_dkms:
	dh_dkms -p wireguard-dkms -- wireguard-src/src/dkms.conf
```
Also I don't like idea to have separate rules file for i386 trusty package.
@EggieCode @zx2c4

**Comment by zx2c4** [comment]
This indeed sucks. Do you know why i386 is different? Is there some debian build rule that's different for that architecture? What's going on?

In any case, if it's easy to just _disable_ trusty/i386 in Launchpad, then maybe that'd make most sense.

By the way, I see you uploaded an x86_64 trusty build, but not yet builds for the other Ubuntus. Could you bump to 20170629 for these too?

**Comment by cryptofuture** [comment]
I didn't uploaded anything (yesterday log was from non official ppa, and I thought this happens only on launchpad, but this happens in any env). I wanted to upload all in bulk, but stuck with that i386 package for trusty. I can upload with hack, but I'm pretty sure should be another way around. And we can't disable i386 for trusty, we can only disable i386 completely. But when builds fails, people who use ppa will see that all other arch beside i386 available for trusty (trusty i386 package will be not in the package manager cache). 
Btw its possible to make hack activated only in trusty on i386 with `ifeq... endif` for example.
>Is there some debian build rule that's different for that architecture? What's going on?

Have no idea. Package rules are the same, and it works with all other i386 versions (xenial, yakkety, zesty)

**Comment by zx2c4** [comment]
Perhaps there's something strange happening where it only really needs to be built for the first platform (amd64), since the dkms package isn't for a particular arch?

**Comment by cryptofuture** [comment]
Ok. I just tested dkms and wg interface with hack in both trusty i386 and xenial x64, and its safe to have hack as it is with another architectures.
I PR and uploading whole things up. 
P.S. Looks like I pressed return in wrong terminal emulator tab yesterday, and uploaded trusty package in official ppa. My bad.

**Comment by EggieCode** [comment]
I think it is the best solution, going to make accept the pull request en close this issue.
